# Generated by Django 4.1.3 on 2022-11-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studyinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit', models.CharField(blank=True, max_length=2000, null=True)),
                ('facility', models.CharField(blank=True, max_length=2000, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('doc_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('scope', models.CharField(blank=True, max_length=2000, null=True)),
                ('objective', models.CharField(blank=True, max_length=2000, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.company')),
            ],
        ),
    ]
